In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [3]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [4]:
x_train

array([15, 16, 12, 11,  6, 19,  1, 14, 13,  5, 17,  2, 20, 10,  9])

In [5]:
len(x_train)

15

In [6]:
y_train

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0])

In [7]:
len(y_train)

15

In [8]:
x_test

array([18,  4,  7,  8,  3])

In [9]:
y_test

array([1, 0, 0, 0, 1])